import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import ReduxConfig from "./redux-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ReduxConfig>{children}</ReduxConfig>
        <Toaster />
      </body>
    </html>
  );
}

// Annotation Type JsonProperty
// "@JsonProperty adalah anotasi yang digunakan untuk menentukan nama properti JSON yang akan dipetakan ke suatu field, method, atau parameter dalam Java.
// com.fasterxml.jackson.annotation"
